[book]
authors = ["huhn511"]
language = "en"
multilingual = false
src = "./page"
title = "IOTA Identity"


[output.html]
# default-theme = "iota"
git-repository-url = "https://github.com/iota-community/X-Team_IOTA_Identity"
git-repository-icon = "fa-github"

# This is for another Sidebar
# additional-css = ["theme/custom/custom.css"]
# additional-css = ["theme/custom/custom.css", "theme/custom/sidebar.css"]
# additional-js = ["theme/custom/sidebar.js"]

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2 